[package]
name = "pdf-redox-cli"
description = "CLI for pdf-redox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "pdf-redox"
path = "src/main.rs"
doc = false

[dependencies]
pdf-redox = { path = "../pdf-redox" }
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
